openapi: 3.0.0

info:
  title: Tambah Order
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in: body
    name: body
    description: Data Order yang akan ditambahkan
    required: true
    schema:
      $ref: '#definitions/Order'
    
responses:
  201:
    description: Data Order berhasil ditambahkan
    schema: 
      $ref: '#definitions/Order'

definitions:
  Order:
    type: object
    properties:
      order_id:
        type: integer
      customer_name:
        type: string
      food_id:
        type: integer
      quantity:
        type: integer
      total_price:
        type: float
      order_date:
        type: date
    required:
      - order_id
      - customer_name
      - food_id
      - quantity
      - total_price
      - order_date