openapi: 3.0.0

info:
  title: Add Order
  version: 1.0.0

tags:
  - name: List API

parameters:
  - in: body
    name: body
    description: Order has been added
    required: true
    schema:
      $ref: '#definitions/Orders'
    
responses:
  201:
    description: Order has been added
    schema: 
      $ref: '#definitions/Orders'

definitions:
  Orders:
    type: object
    properties:
      order_id:
        type: string
      customer_name:
        type: string
      food_id:
        type: string
      quantity:
        type: integer
      total_price:
        type: number
      order_date:
        type: date
    required:
      - order_id
      - customer_name
      - food_id
      - quantity
      - total_price
      - order_date
