openapi: 3.0.0

info:
  title: Add Food
  version: 1.0.0

tags:
  - name: List API

parameters:
  - in: body
    name: body
    description: Add Food
    required: true
    schema:
      $ref: '#definitions/Food'
    
responses:
  201:
    description: Food Data Added
    schema: 
      $ref: '#definitions/Food'

definitions:
  Food:
    type: object
    properties:
      food_id:
        type: integer
      name:
        type: string
      price:
        type: number
      category:
        type: string
    required:
      - food_id
      - name
      - price
      - category