openapi: 3.0.0
info:
  title: Delete Order
  version: 1.0.0
tags:
  - name: List API
parameters:
  - name: order_id
    in: path
    description: Deleted Order
    required: true
    type: integer
responses:
  200:
    descriptions: Order has been removed
  404:
    descriptions: Data not found