openapi: 3.0.0
info:
  title: Get All Food
  version: 1.0.0
tags:
  - name: List API
definitions:
  Order:
    type: object
    properties:
      order_id:
        type: integer
        description: Order ID
      customer_name:
        type: string
        description: Customer Name
      name:
        type: string
        description: Food Name
      quantity:
        type: integer
        description: Food quantity
      total_price:
        type: number
        description: Total Price
      order_date:
        type: string
        description: Order Date

responses:
  200:
    descriptions: All Data
    schema:
      type: array
      items:
        $ref: '#/definitions/Order'

