openapi: 3.0.0
info:
  title: Update Order
  version: 1.0.0
tags:
  - name: List API
definitions:
  Order:
    type: object
    properties:
      customer_name:
        type: string
        description: Customer Name
      food_id:
        type: string
        description: Food ID
      quantity:
        type: integer
        description: Quantity
      total_price:
        type: number
        description: total price
parameters:
  - name: order_id
    in: path
    description: Order id updated
    required: true
    type: integer
  - in: body
    name: body
    descriptions: Order data will be update
    required: true
    schema:
      $ref: '#/definitions/Order'

responses:
  200:
    descriptions: Order Data has been updated
    schema:
      $ref: '#/definitions/Order'
  404:
    descriptions: Order Data not found
