openapi: 3.0.0
info:
  title: Update Food
  version: 1.0.0
tags:
  - name: List API
definitions:
  Food:
    type: object
    properties:
      food_id:
        type: string
        description: Food ID
      name:
        type: string
        description: Food Name
      price:
        type: number
        description: Food Price
      category:
        type: string
        description: Food Category

parameters:
  - name: food_id
    in: path
    description: Food id updated
    required: true
    type: integer
  - in: body
    name: body
    descriptions: Food data will be update
    required: true
    schema:
      $ref: '#/definitions/Food'

responses:
  200:
    descriptions: Food Data has been updated
    schema:
      $ref: '#/definitions/Food'
  404:
    descriptions: Food Data not found
